all:
  hosts:
    myserver:
      ansible_host: 92.118.113.15
      ansible_user: root
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    
    # Эксперементирую с впн ваир 
    myserver2:
      ansible_host: 194.87.76.208
      ansible_user: root
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
