all:
  hosts:
    myserver:
      ansible_host: 92.118.113.15
      ansible_user: root
    
    # Эксперементирую с впн ваир 
    myserver2:
      ansible_host: 217.198.6.135
      ansible_user: root

    server_3:
      ansible_host: 89.223.68.14
      ansible_user: root
