all:
  hosts:
    myserver:
      ansible_host: 92.118.113.15
      ansible_user: root
    
    # Эксперементирую с впн ваир 
    myserver2:
      ansible_host: 217.198.6.135
      ansible_user: root

    server_3:
      ansible_host: 89.223.68.14
      ansible_user: root

    # aeza
    server_4:
      ansible_host: 77.110.114.51
      ansible_user: root
      ansible_ssh_pass: S9NPY3IJaZNi
      ansible_become_pass: S9NPY3IJaZNi

  children:
    install_docker:
      hosts:
        server_5: